### ISSUE TITLE
Ras Pi 4B   ModuleNotFoundError: No module named 'BASE' 

### ISSUE THREAD

**Issue by arhyneRWU** [pi-plates/TINKERplate-Projects#1]
Running python 3 on freshly updated Ras Pi 4B. 
```

Traceback (most recent call last):
  File "TINKdash.py", line 1, in <module>
    import piplates.TINKERplate as TINK
  File "/usr/local/lib/python3.7/dist-packages/piplates/TINKERplate.py", line 13, in <module>
    from BASE import *

```

**Comment by arhyneRWU** [comment]
I do have SPI enabled.

**Comment by arhyneRWU** [comment]
found issue renamed **Base.py** to **BASE.PY** in the dir below
```
pi@raspberrypi:~/PYTHONmodules $ ls
A2D.py     BUTTON.py      DAQChelp.txt  LED.py         MOTORplate.py  README.md      RELAY.py  THERMOhelp.txt  TINKERplate.py
ANFUNC.py  DAQC2help.txt  DAQCplate.py  METER.py       PWM.py         RELAYhelp.txt  SERVO.py  THERMOplate.py
**Base.py**    DAQC2plate.py  DIO.py        MOTORhelp.txt  RANGE.py       RELAYplate.py  TEMP.py   TINKERhelp.txt
```

**Comment by arhyneRWU** [comment]
Fixed this by renaming **Base.py** to **BASE.py**

```
A2D.py     DAQC2help.txt  DIO.py       MOTORhelp.txt  PWM.py         RELAYplate.py  THERMOhelp.txt
ANFUNC.py  DAQC2plate.py  __init__.py  MOTORplate.py  __pycache__    RELAY.py       THERMOplate.py
**Base.py**    DAQChelp.txt   LED.py       POWERhelp.txt  RANGE.py       SERVO.py       TINKERhelp.txt
BUTTON.py  DAQCplate.py   METER.py     POWERplate.py  RELAYhelp.txt  TEMP.py        TINKERplate.py
```

**Comment by pi-plates** [comment]
Thanks - this has been addressed and the repository has been updated.
